### PR TITLE
Remove checking remote description has different ICE credentials

### PR DESCRIPTION
**Pull request by xicilion**
In the WebRTC Direct protocol, we need to allow local and remote to use the same ufrag and pwd.

### CODE REVIEW

**Comment by paullouisageneau** [comment]
I get the idea, but this disables a useful check (it's common for users to mess up signaling and send back the description into the same peer connection). I wonder if there is a way to check for such a scenario that doesn't rely on ICE attributes.

**Comment by xicilion** [comment]
Or we can leave that choice to the developers and provide an option to disable it.

**Comment by xicilion** [comment]
mSessionId is randomly generated each time, the probability of duplication is very small, is it possible to check if mSessionId is equal?

**Comment by xicilion** [comment]
@paullouisageneau how about check mSessionId?

**Comment by paullouisageneau** [comment]
It makes sense, the problem is that while session id is currently randomly generated in libdatachannel, it is not guaranteed to be unique between endpoints (other implementations typically use a timestamp), so it feels a bit clumsy. Since I've no better idea, I think you can remove the check.

**Review by paullouisageneau — APPROVED** [review]

**Pull request merged**
