### PR TITLE
Fix the compilation issue on the Windows platform.

### PR DESCRIPTION
**Pull request by CapricornFBQ**
1. Fix the compilation issue on the Windows platform by include parts of the standard library.
2. Fix the issue where exporting the "defaultClockRate" static variable in datachannel.lib/dll fails on the Windows platform.

### CODE REVIEW

**Comment by paullouisageneau** [comment]
Please don't change submodules, currently the build is broken as a result.

The library [builds fine with MSVC](https://github.com/paullouisageneau/libdatachannel/actions/runs/9301905746/job/25600987843), what is your setup?

>  2. Fix the issue where exporting the "defaultClockRate" static variable in datachannel.lib/dll fails on the Windows platform.

What is the problem exactly and why would Windows require special treatment? Static variables must be inline, otherwise it's just a declaration and there must be a definition outside the class, that's why you hit "undefined reference" errors at first.

**Comment by CapricornFBQ** [comment]
I apologize for not providing the context for the issue initially. I am using Visual Studio 2017 with SDK version 10.0.17763.0. When I compile examples/streamer, there is an issue where `defaultClockRate` is not defined. After troubleshooting, I found that the ”datachannel.dll“ did not export this variable. It appears that on the Windows platform, there is a conflict when using `inline `and `__declspec(dllexport)` together. Could you please verify this for me?

**Comment by paullouisageneau** [comment]
I'm okay to fix the includes but the issue with `inline` and `__declspec(dllexport)` seems to be an issue with Visual Studio 2017. Again, in [builds fine](https://github.com/paullouisageneau/libdatachannel/actions/runs/9301905746/job/25600987843) on Windows with Visual Studio 2022 with MSVC MSVC 19.39.33523.0. Have you tried with a more recent version?

**Comment by paullouisageneau** [comment]
I'd be OK to fix the includes but the issue with `inline` and `__declspec(dllexport)` seems to be an issue with Visual Studio 2017. Again, the library [builds fine](https://github.com/paullouisageneau/libdatachannel/actions/runs/9301905746/job/25600987843) on Windows with Visual Studio 2022 with MSVC MSVC 19.39.33523.0. Have you tried with a more recent version?

**Comment by paullouisageneau** [comment]
Closing in favor of https://github.com/paullouisageneau/libdatachannel/pull/1280

**Pull request closed without merging**
