### PR TITLE
Add FrameInfo

### PR DESCRIPTION
**Pull request by Sean-Der**
Depacketizers will include metadata about assembled frame.

### CODE REVIEW

**Comment by Sean-Der** [comment]
@paullouisageneau this is ready for review, thank you!

**Comment by Sean-Der** [comment]
@paullouisageneau :+1: will fix that now!

**Comment by Sean-Der** [comment]
@paullouisageneau done! Can I get another review please?

**Review by paullouisageneau — COMMENTED** [review]
I have a couple nitpicks, but otherwise it looks good, thanks for the work!

**Pull request closed without merging**
